/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#dcd9d9",
        "on-tertiary-container": "#fff9f9",
        "on-secondary-container": "#fefcff",
        "secondary-container": "#2670e3",
        "surface-container-low": "#f6f3f2",
        "inverse-surface": "#313030",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#eeffed",
        "inverse-on-surface": "#f3f0ef",
        "tertiary-fixed-dim": "#ffb2b8",
        "background": "#FFFFFF",
        "border-light": "#E5E7EB",
        "secondary-fixed-dim": "#aec6ff",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container-high": "#ebe7e7",
        "inverse-primary": "#71dc92",
        "on-secondary-fixed-variant": "#004396",
        "surface-tint": "#006d38",
        "surface-container-highest": "#e5e2e1",
        "on-tertiary-fixed": "#40000f",
        "on-secondary-fixed": "#001a42",
        "outline": "#6e7a6f",
        "secondary": "#0057bf",
        "surface-subtle": "#F3F4F6",
        "on-background": "#1c1b1b",
        "surface-bright": "#fcf9f8",
        "primary-container": "#008545",
        "tertiary-fixed": "#ffdadb",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#832334",
        "outline-variant": "#bdcabc",
        "tertiary-container": "#bd4f5e",
        "on-primary-fixed": "#00210d",
        "secondary-fixed": "#d8e2ff",
        "surface-variant": "#e5e2e1",
        "on-tertiary": "#ffffff",
        "primary": "#006935",
        "tertiary": "#9d3747",
        "surface-container": "#f0edec",
        "primary-fixed-dim": "#71dc92",
        "on-surface-variant": "#3e4a3f",
        "status-warning": "#F59E0B",
        "surface": "#fcf9f8",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#005228",
        "on-surface": "#1c1b1b",
        "primary-fixed": "#8df9ac",
        "error-container": "#ffdad6"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "16px",
        "container-padding": "24px",
        "stack-md": "16px",
        "stack-sm": "8px",
        "stack-lg": "32px",
        "unit": "4px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "data-numeric": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-lg": ["28px", {"lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-sm": ["16px", {"lineHeight": "24px", "fontWeight": "600"}],
        "label-sm": ["11px", {"lineHeight": "14px", "fontWeight": "500"}],
        "data-numeric": ["15px", {"lineHeight": "20px", "letterSpacing": "0px", "fontWeight": "600"}],
        "headline-md": ["20px", {"lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
      }
    }
  },
  plugins: [],
}
